function [integ] = Integral(x ,y, panel, dxdk, dydk)
%INTEGRAL determined what the contribution of the vortex strength of a 
%   panel is to another point

% integrand = (((x - (panel.xa - sin(panel.beta) * s))*dxdk +...
%                  (y - (panel.ya + cos(panel.beta) * s)) * dydk) /...
%                 ((x - (panel.xa - sin(panel.beta) * s))^2 +...
%                  (y - (panel.ya + cos(panel.beta) * s))^2) );
             
     fun =@(x,y,panel,dxdk,dydk,s)...
        ((x-(panel.xa - sin(panel.beta).* s)).* dxdk +...
        (y - (panel.ya + cos(panel.beta).* s)).* dydk)./...
        ((x - (panel.xa - sin(panel.beta).* s)).^2 +...
        (y - (panel.ya + cos(panel.beta).* s)).^2);
    
    integ = integral(@(s) fun(x,y,panel,dxdk,dydk,s),0,panel.length,'ArrayValued',true);
% integ = quadv(@(s) fun(x,y,panel,dxdk,dydk,s),0,panel.length,'ArrayValued',true);
end

